version: '3'
services:
  app:
    build: .
    env_file:
      - .env.sample
    ports:
      - '8000:8000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    command: 
      /docker-entrypoint-initdb.d/import.sh
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    