[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88

[tool.pytest.ini_options]
filterwarnings = [
    # ignore starlette DeprecationWarning - FastAPI depends on starlette 0.14.2, so can't upgrade module
    "ignore:'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.:DeprecationWarning"
]