---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: titanic
    tier: database
spec:
  ports:
    - port: 27017
  selector:
    app: titanic
    tier: database
  clusterIP: None
